version: "3"

services:
  node:
    build: docker/node
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - .:/home/node
